name: ci

on:
  push:
    branches: ["mistress"]
  pull_request:
    branches: ["mistress"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: setup repo
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2.0.3
      
      - name: install pixz
        run: sudo apt install pixz

      - name: install deps
        run: deno install --allow-import

      - name: compile
        run: deno task compile

      - name: compress
        run: deno task compress

      - name: upload linux artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: linux
          path: cs2-presence.xz
          
      - name: upload windows artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: windows
          path: cs2-presence.exe.xz
